---
- hosts: dbservers
  become: true
  tasks:
    - name: Install apache httpd
      ansible.builtin.yum:
        name: httpd
        state: present
        update_cache: yes
      # The 'yum' module also works for dnf-based systems.

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html # Ensure a filename is specified in the destination
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      # This task ensures the service is running and starts automatically at boot.

    # Optional: Open firewall ports if firewalld is active
    - name: Allow http service in firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      # You might need to install the 'ansible.posix' collection first.